const { calculateNutriScore2022, transformResponse } = require("./content.js");

describe("Nutri-Score 2022 Algorithm Tests", () => {
  test("Bohemia Solene", async () => {
    const score = calculateNutriScore2022({
      energyKJ: 2295,
      proteins: 1.4,
      carbs: 58,
      sugars: null,
      fats: 34,
      saturatedFats: 16.2,
      fiber: 3.4,
      salt: 2.9,
    });
    expect(score).toEqual("D");
  });

  describe("General Foods (Updated Algorithm)", () => {
    const generalFoodCases = [
      {
        name: "Apple sauce tinned",
        energyKJ: 321.0,
        sugars: 17.1,
        saturatedFats: 0,
        salt: 0.025,
        fiber: 1.9,
        proteins: 0.2,
        fruitVegLegumesPercent: 90, // Apple sauce should have high fruit content
        expected: "A",
      },
      {
        name: "Sugar granulated",
        energyKJ: 1700.0,
        sugars: 100.0,
        saturatedFats: 0,
        salt: 0,
        fiber: 0,
        proteins: 0,
        fruitVegLegumesPercent: 0,
        expected: "E",
      },
      {
        name: "protein 1",
        energyKJ: 1501.0,
        sugars: 3.3,
        saturatedFats: 5.8,
        salt: 0.34,
        fiber: 9.8,
        proteins: 25.0,
        fruitVegLegumesPercent: 0,
        expected: "A",
      },
      {
        name: "protein 2",
        energyKJ: 1523.0,
        sugars: 3.3,
        saturatedFats: 6.7,
        salt: 0.3,
        fiber: 10.0,
        proteins: 25.0,
        fruitVegLegumesPercent: 0,
        expected: "C",
      },
      {
        name: "M&S Fruit & Nut Muesli",
        energyKJ: 1730.0,
        sugars: 3.5,
        saturatedFats: 2.0,
        salt: 0.03,
        fiber: 13.3,
        proteins: 13.8,
        fruitVegLegumesPercent: 0,
        expected: "A",
      },
      {
        name: "M&S Berry and Cherry flakes",
        energyKJ: 1571.0,
        sugars: 11.9,
        saturatedFats: 0.2,
        salt: 0.45,
        fiber: 3.1,
        proteins: 8.7,
        fruitVegLegumesPercent: 0,
        expected: "C",
      },
      {
        name: "white bread",
        energyKJ: 1109.0,
        sugars: 0,
        saturatedFats: 0.5,
        salt: 0.9,
        fiber: 0,
        proteins: 9.0,
        fruitVegLegumesPercent: 0,
        expected: "C",
      },
      {
        name: "toast bread",
        energyKJ: 1055.0,
        sugars: 3.2,
        saturatedFats: 0.3,
        salt: 1.0,
        fiber: 6.0,
        proteins: 8.5,
        fruitVegLegumesPercent: 0,
        expected: "B",
      },
      {
        name: "kapsicka biely jogurt Miil",
        energyKJ: 477.0,
        sugars: 3.3,
        saturatedFats: 6.5,
        salt: 0.1,
        fiber: 0,
        proteins: 3.0,
        fruitVegLegumesPercent: 0,
        expected: "C",
      },
      {
        name: "biely jogurt miil",
        energyKJ: 278.0,
        sugars: 4.4,
        saturatedFats: 2.6,
        salt: 0.1,
        fiber: 0,
        proteins: 3.9,
        fruitVegLegumesPercent: 0,
        expected: "B",
      },
      {
        name: "Rohlik.cz Hummus classico",
        energyKJ: 1342.0,
        sugars: 0.6,
        saturatedFats: 4.2,
        salt: 0.82,
        fiber: 0,
        proteins: 5.8,
        fruitVegLegumesPercent: 0,
        expected: "D",
      },
      {
        name: "Emco Super sušenky bez přidaného cukru kakao a Kokos",
        energyKJ: 1863.0,
        sugars: 6.3,
        saturatedFats: 7.6,
        salt: 0.05,
        fiber: 14.0,
        proteins: 9.8,
        fruitVegLegumesPercent: 0,
        expected: "C",
      },
      {
        name: "Emco Super sušenky bez přidaného cukru šťavnaté jablko",
        energyKJ: 1782.0,
        sugars: 12.0,
        saturatedFats: 3.9,
        salt: 0.04,
        fiber: 9.8,
        proteins: 9.0,
        fruitVegLegumesPercent: 0,
        expected: "C",
      },
    ];

    test.each(generalFoodCases)("$name => expected $expected", (testCase) => {
      const score = calculateNutriScore2022(testCase);
      expect(score).toBe(testCase.expected);
    });
  });

  describe("Cheese Products (Updated Algorithm)", () => {
    const cheeseCases = [
      {
        name: "Cheese",
        energyKJ: 1523.0,
        sugars: 0.5,
        saturatedFats: 19.8,
        salt: 1.8,
        fiber: 0.1,
        proteins: 24.1,
        fruitVegLegumesPercent: 0,
        expected: "D",
        isCheese: true,
      },
      {
        name: "Solid and semi-solid cheese",
        energyKJ: 1568.0,
        sugars: 0,
        saturatedFats: 20.2,
        salt: 1.8,
        fiber: 0,
        proteins: 26.1,
        fruitVegLegumesPercent: 0,
        expected: "D",
        isCheese: true,
      },
      {
        name: "Soft cheese",
        energyKJ: 1344.0,
        sugars: 2.6,
        saturatedFats: 18.4,
        salt: 1.6,
        fiber: 0.3,
        proteins: 15.4,
        fruitVegLegumesPercent: 0,
        expected: "D",
        isCheese: true,
      },
      {
        name: "Processed cheese",
        energyKJ: 1242.0,
        sugars: 1.0,
        saturatedFats: 15.6,
        salt: 2.3,
        fiber: 0,
        proteins: 19.4,
        fruitVegLegumesPercent: 0,
        expected: "D",
        isCheese: true,
      },
      {
        name: "madeland 20%",
        energyKJ: 943.0,
        sugars: 0.5,
        saturatedFats: 7.2,
        salt: 1.3,
        fiber: 0,
        proteins: 31.0,
        fruitVegLegumesPercent: 0,
        expected: "C",
        isCheese: true,
      },
      {
        name: "Meggle Cottage Cheese přírodní",
        energyKJ: 385.0,
        sugars: 1.5,
        saturatedFats: 2.8,
        salt: 1.1,
        fiber: 0,
        proteins: 12.0,
        fruitVegLegumesPercent: 0,
        expected: "C",
        isCheese: true,
      },
    ];

    test.each(cheeseCases)("$name => expected $expected", (testCase) => {
      const score = calculateNutriScore2022(testCase);
      expect(score).toBe(testCase.expected);
    });
  });
});
